[package]
name = "ludum-dare-48"
version = "0.1.0"
authors = ["Evan Pratten <ewpratten@gmail.com>"]
edition = "2018"
description = ""

[dependencies]
raylib = { version = "3.5", git = "https://github.com/ewpratten/raylib-rs", branch = "master" }

